### ISSUE TITLE
Нужен обучающий ролик. 

### ISSUE THREAD

**Issue by IVIiracle** [reriiasu/speech-to-text#7]
Предварительно очень нужная программа, но у меня не получается никак сделать так, чтобы она работала. Запускается, да. Но не могу выбрать нужный вариант Audio Device. Выходит, что запить идет, но ничего не происходит. Перепробовал все возможные, как быть? 

Извини, если вопрос слишком глупый, но как еще?)

**Comment by reriiasu** [comment]
IVIiracle Привет

Ответом будет перевод.

Устройством ввода будет микрофон, поэтому микрофон необходимо подключить к ПК.
Другой вариант — использовать виртуальные аудиоустройства для обеспечения звуков рабочего стола.

**Comment by IVIiracle** [comment]
> IVIiracle Привет
> 
> Ответом будет перевод.
> 
> Устройством ввода будет микрофон, поэтому микрофон необходимо подключить к ПК. Другой вариант — использовать виртуальные аудиоустройства для обеспечения звуков рабочего стола.

Спасибо за то, что отвечаешь на моем языке, это приятно) Смотри, либо выбираю свой микрофон и запись идет, но ничего не выводится, либо ошибка:: Error opening InputStream: Invalid number of channels [PaErrorCode -9998]. Когда пытаюсь транскрибировать файл, то ошибка: Input audio chunk is too short (длина где-то 20 секунд).

**Comment by IVIiracle** [comment]
В общем, не знаю как быть, сейчас попробую с виртуальным кабелем, но что-то не особо верится, что получится что-то.

**Comment by reriiasu** [comment]
Если возникает следующая ошибка, это неправильный выбор.
Error opening InputStream: Invalid number of channels [PaErrorCode -9998]. 

Правильно ли работает вход микрофона в Windows?
Я указываю и использую "xxxxxxx MME (2 in)".

**Comment by reriiasu** [comment]
Удалось ли вам узнать микрофон, выполнив следующие действия?
Если он не распознается, используйте другой микрофон.

https://support.microsoft.com/ru-ru/windows/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0 %B0-%D0%B8-%D0%BF%D1%80%D0%BE%D0%B2%D0%B5%D1%80%D0%BA%D0%B0-%D0%BC%D0%B8% D0%BA%D1%80%D0%BE%D1%84%D0%BE%D0%BD%D0%BE%D0%B2-%D0%B2-windows-ba9a4aab-35d1-12ee-5835-cccac7ee87a4

**Comment by reriiasu** [comment]
Это было хорошо.
